// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events_outbox.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingEvents = `-- name: ClaimPendingEvents :many
WITH claimable AS (
    SELECT id
    FROM events_outbox
    WHERE (
        status = 'pending'
        OR (status = 'processing' AND claimed_at < NOW() - $1::interval)
    )
      AND available_at <= NOW()
    ORDER BY available_at ASC
    LIMIT $2::int
    FOR UPDATE SKIP LOCKED
)
UPDATE events_outbox AS outbox
SET
    status = 'processing',
    claimed_at = NOW(),
    attempts = attempts + 1
FROM claimable
WHERE outbox.id = claimable.id
RETURNING outbox.id, outbox.aggregate_type, outbox.aggregate_id, outbox.event_type, outbox.payload, outbox.headers, outbox.available_at, outbox.published_at, outbox.attempts, outbox.last_error, outbox.delivered, outbox.created_at, outbox.status, outbox.claimed_at
`

type ClaimPendingEventsParams struct {
	Lease pgtype.Interval `db:"lease" json:"lease"`
	Limit int32           `db:"limit" json:"limit"`
}

func (q *Queries) ClaimPendingEvents(ctx context.Context, arg ClaimPendingEventsParams) ([]EventsOutbox, error) {
	rows, err := q.db.Query(ctx, claimPendingEvents, arg.Lease, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventsOutbox
	for rows.Next() {
		var i EventsOutbox
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.Headers,
			&i.AvailableAt,
			&i.PublishedAt,
			&i.Attempts,
			&i.LastError,
			&i.Delivered,
			&i.CreatedAt,
			&i.Status,
			&i.ClaimedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events_outbox
WHERE id = $1::bigint
`

func (q *Queries) DeleteEvent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const enqueueEvent = `-- name: EnqueueEvent :one
INSERT INTO events_outbox (
    aggregate_type,
    aggregate_id,
    event_type,
    payload,
    headers,
    available_at,
    status,
    claimed_at
)
VALUES (
    $1::text,
    $2::text,
    $3::text,
    COALESCE($4::jsonb, '{}'::jsonb),
    COALESCE($5::jsonb, '{}'::jsonb),
    COALESCE($6::timestamptz, NOW()),
    'pending',
    NULL
)
RETURNING id, aggregate_type, aggregate_id, event_type, payload, headers, available_at, published_at, attempts, last_error, delivered, created_at, status, claimed_at
`

type EnqueueEventParams struct {
	AggregateType string             `db:"aggregate_type" json:"aggregate_type"`
	AggregateID   string             `db:"aggregate_id" json:"aggregate_id"`
	EventType     string             `db:"event_type" json:"event_type"`
	Payload       []byte             `db:"payload" json:"payload"`
	Headers       []byte             `db:"headers" json:"headers"`
	AvailableAt   pgtype.Timestamptz `db:"available_at" json:"available_at"`
}

func (q *Queries) EnqueueEvent(ctx context.Context, arg EnqueueEventParams) (EventsOutbox, error) {
	row := q.db.QueryRow(ctx, enqueueEvent,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.Headers,
		arg.AvailableAt,
	)
	var i EventsOutbox
	err := row.Scan(
		&i.ID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.Headers,
		&i.AvailableAt,
		&i.PublishedAt,
		&i.Attempts,
		&i.LastError,
		&i.Delivered,
		&i.CreatedAt,
		&i.Status,
		&i.ClaimedAt,
	)
	return i, err
}

const markEventDelivered = `-- name: MarkEventDelivered :one
UPDATE events_outbox
SET
    status = 'delivered',
    delivered = TRUE,
    published_at = NOW(),
    claimed_at = NULL,
    last_error = NULL
WHERE id = $1::bigint
RETURNING id, aggregate_type, aggregate_id, event_type, payload, headers, available_at, published_at, attempts, last_error, delivered, created_at, status, claimed_at
`

func (q *Queries) MarkEventDelivered(ctx context.Context, id int64) (EventsOutbox, error) {
	row := q.db.QueryRow(ctx, markEventDelivered, id)
	var i EventsOutbox
	err := row.Scan(
		&i.ID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.Headers,
		&i.AvailableAt,
		&i.PublishedAt,
		&i.Attempts,
		&i.LastError,
		&i.Delivered,
		&i.CreatedAt,
		&i.Status,
		&i.ClaimedAt,
	)
	return i, err
}

const resetEventForRetry = `-- name: ResetEventForRetry :one
UPDATE events_outbox
SET
    status = 'pending',
    delivered = FALSE,
    claimed_at = NULL,
    last_error = $1::text,
    available_at = NOW() + INTERVAL '30 seconds'
WHERE id = $2::bigint
  AND status IN ('pending', 'processing')
RETURNING id, aggregate_type, aggregate_id, event_type, payload, headers, available_at, published_at, attempts, last_error, delivered, created_at, status, claimed_at
`

type ResetEventForRetryParams struct {
	LastError string `db:"last_error" json:"last_error"`
	ID        int64  `db:"id" json:"id"`
}

func (q *Queries) ResetEventForRetry(ctx context.Context, arg ResetEventForRetryParams) (EventsOutbox, error) {
	row := q.db.QueryRow(ctx, resetEventForRetry, arg.LastError, arg.ID)
	var i EventsOutbox
	err := row.Scan(
		&i.ID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.Headers,
		&i.AvailableAt,
		&i.PublishedAt,
		&i.Attempts,
		&i.LastError,
		&i.Delivered,
		&i.CreatedAt,
		&i.Status,
		&i.ClaimedAt,
	)
	return i, err
}
