# environment: deployment environment (dev | staging | prod)
environment: dev

exchanges:
  # fake-liquid: moderate volatility venue demonstrating instrument refresh and klines
  fake-liquid:
    exchange:
      name: fake
      enabled: true
      ticker_interval: 150ms
      trade_interval: 120ms
      book_snapshot_interval: 400ms
      instrument_refresh_interval: 15m
      kline_interval: 30s
      price_model:
        drift: 0.00018
        volatility: 0.009
        shock_probability: 0.02
        shock_magnitude: 0.015
      trade_model:
        min_quantity: 0.02
        max_quantity: 1.5
      order_book:
        levels: 14
        max_mutation_width: 6
      venue_behavior:
        latency_min: 8ms
        latency_max: 28ms
        transient_error: 0.0025
        disconnect_chance: 0.0002
        disconnect_for: 2s
  # fake-volatile: fast-moving market with aggressive shocks for stress tests
  fake-volatile:
    exchange:
      name: fake
      enabled: true
      ticker_interval: 80ms
      trade_interval: 60ms
      book_snapshot_interval: 200ms
      kline_interval: 15s
      price_model:
        drift: 0.00035
        volatility: 0.02
        shock_probability: 0.08
        shock_magnitude: 0.05
      trade_model:
        min_quantity: 0.01
        max_quantity: 2.8
      order_book:
        levels: 18
        max_mutation_width: 9
      venue_behavior:
        latency_min: 4ms
        latency_max: 18ms
        transient_error: 0.006
        disconnect_chance: 0.001
        disconnect_for: 1500ms
  # fake-calm: slower venue illustrating tight error budgets and wider latency bands
  fake-calm:
    exchange:
      name: fake
      enabled: true
      ticker_interval: 250ms
      trade_interval: 250ms
      book_snapshot_interval: 1s
      instrument_refresh_interval: 20m
      kline_interval: 1m
      price_model:
        drift: 0.00005
        volatility: 0.004
        shock_probability: 0.01
        shock_magnitude: 0.01
      trade_model:
        min_quantity: 0.05
        max_quantity: 1.0
      order_book:
        levels: 10
        max_mutation_width: 4
      venue_behavior:
        latency_min: 12ms
        latency_max: 45ms
        transient_error: 0.0015
        disconnect_chance: 0.00005
        disconnect_for: 4s

# eventbus: in-memory event bus sizing
eventbus:
  bufferSize: 5000
  fanoutWorkers: 8

# pools: object pool capacities
pools:
  eventSize: 25000
  orderRequestSize: 5000

# apiServer: control API bind address (host:port or :port)
apiServer:
  addr: ":8880"

# telemetry: OTLP exporter configuration
telemetry:
  otlpEndpoint: http://capy.lan:4318
  serviceName: meltica-gateway
  otlpInsecure: true
  enableMetrics: true

# lambdaManifest: inline lambda definitions that will be materialised at startup
lambdaManifest:
  lambdas:
    - id: mm-btc
      provider: fake-liquid
      symbol: BTC-USDT
      strategy: marketmaking
      config:
        spread_bps: 28
        order_size: "0.05"
        max_open_orders: 3
      auto_start: true
    - id: grid-eth
      provider: fake-volatile
      symbol: ETH-USDT
      strategy: grid
      config:
        grid_levels: 5
        grid_spacing: 0.75
        order_size: "0.4"
      auto_start: true
    - id: momentum-sol
      provider: fake-volatile
      symbol: SOL-USDT
      strategy: momentum
      config:
        lookback_period: 24
        momentum_threshold: 0.9
        order_size: "12"
        cooldown: "4s"
      auto_start: true
    - id: meanrev-xrp
      provider: fake-calm
      symbol: XRP-USDT
      strategy: meanreversion
      config:
        window_size: 30
        deviation_threshold: 0.7
        order_size: "2500"
      auto_start: true
    - id: logging-ada
      provider: fake-liquid
      symbol: ADA-USDT
      strategy: logging
      config:
        logger_prefix: "[ADA-LOGGER] "
      auto_start: true
    - id: delay-doge
      provider: fake-calm
      symbol: DOGE-USDT
      strategy: delay
      config:
        min_delay: "150ms"
        max_delay: "600ms"
      auto_start: true
    - id: noop-bnb
      provider: fake-liquid
      symbol: BNB-USDT
      strategy: noop
      auto_start: true
