environment: prod

exchanges:
  binance:
    exchange:
      name: binance
      venue: spot
      enabled: true
      snapshot_depth: 100
  binance-futures:
    exchange:
      name: binance
      venue: futures
      enabled: true
      snapshot_depth: 100

eventbus:
  bufferSize: 8192
  fanoutWorkers: auto

pools:
  eventSize: 60000
  orderRequestSize: 20000

risk:
  maxPositionSize: "100"
  maxNotionalValue: "25000"
  notionalCurrency: "USDT"
  orderThrottle: 2.5
  orderBurst: 2
  maxConcurrentOrders: 5
  priceBandPercent: 0.8
  allowedOrderTypes:
    - Limit
    - Market
  killSwitchEnabled: true
  maxRiskBreaches: 3
  circuitBreaker:
    enabled: true
    threshold: 4
    cooldown: 60s

apiServer:
  addr: ":8880"

telemetry:
  otlpEndpoint: http://capy.lan:4318
  serviceName: meltica-gateway-binance
  otlpInsecure: true
  enableMetrics: true

lambdaManifest:
  lambdas:
    - id: binance-log-btc
      providers:
        - binance
      symbol: BTC-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-SPOT] "
      auto_start: true
    - id: binance-log-eth
      providers:
        - binance
      symbol: ETH-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-SPOT] "
      auto_start: true
    - id: binance-log-bnb
      providers:
        - binance
      symbol: BNB-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-SPOT] "
      auto_start: true
    - id: binance-log-xrp
      providers:
        - binance
      symbol: XRP-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-SPOT] "
      auto_start: true
    - id: binance-log-sol
      providers:
        - binance
      symbol: SOL-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-SPOT] "
      auto_start: true
    - id: binance-log-ada
      providers:
        - binance
      symbol: ADA-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-SPOT] "
      auto_start: true
    - id: binance-log-doge
      providers:
        - binance
      symbol: DOGE-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-SPOT] "
      auto_start: true
    - id: binance-log-ltc
      providers:
        - binance
      symbol: LTC-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-SPOT] "
      auto_start: true
    - id: binance-log-link
      providers:
        - binance
      symbol: LINK-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-SPOT] "
      auto_start: true
    - id: binance-log-trx
      providers:
        - binance
      symbol: TRX-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-SPOT] "
      auto_start: true
    - id: binance-log-matic
      providers:
        - binance
      symbol: MATIC-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-SPOT] "
      auto_start: true
    - id: binance-log-avax
      providers:
        - binance
      symbol: AVAX-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-SPOT] "
      auto_start: true
    - id: binance-log-dot
      providers:
        - binance
      symbol: DOT-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-SPOT] "
      auto_start: true
    - id: binance-log-atom
      providers:
        - binance
      symbol: ATOM-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-SPOT] "
      auto_start: true
    - id: binance-log-fil
      providers:
        - binance
      symbol: FIL-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-SPOT] "
      auto_start: true
    - id: binance-cross-log
      providers:
        - binance
        - binance-futures
      symbol: ETH-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-CROSS] "
      auto_start: true
    - id: binance-cross-log-btc
      providers:
        - binance
        - binance-futures
      symbol: BTC-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-CROSS] "
      auto_start: true
    - id: binance-cross-log-sol
      providers:
        - binance
        - binance-futures
      symbol: SOL-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-CROSS] "
      auto_start: true
    - id: binance-cross-log-ada
      providers:
        - binance
        - binance-futures
      symbol: ADA-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-CROSS] "
      auto_start: true
    - id: binance-cross-log-doge
      providers:
        - binance
        - binance-futures
      symbol: DOGE-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-CROSS] "
      auto_start: true
    - id: binance-cross-log-xrp
      providers:
        - binance
        - binance-futures
      symbol: XRP-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-CROSS] "
      auto_start: true
    - id: binance-cross-log-near
      providers:
        - binance
        - binance-futures
      symbol: NEAR-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-CROSS] "
      auto_start: true
    - id: binance-cross-log-ftm
      providers:
        - binance
        - binance-futures
      symbol: FTM-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-CROSS] "
      auto_start: true
    - id: binance-cross-log-sand
      providers:
        - binance
        - binance-futures
      symbol: SAND-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-CROSS] "
      auto_start: true
    - id: binance-cross-log-axs
      providers:
        - binance
        - binance-futures
      symbol: AXS-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-CROSS] "
      auto_start: true
    - id: binance-futures-log-btc
      providers:
        - binance-futures
      symbol: BTC-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-FUTURES] "
      auto_start: true
    - id: binance-futures-log-eth
      providers:
        - binance-futures
      symbol: ETH-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-FUTURES] "
      auto_start: true
    - id: binance-futures-log-bnb
      providers:
        - binance-futures
      symbol: BNB-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-FUTURES] "
      auto_start: true
    - id: binance-futures-log-xrp
      providers:
        - binance-futures
      symbol: XRP-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-FUTURES] "
      auto_start: true
    - id: binance-futures-log-sol
      providers:
        - binance-futures
      symbol: SOL-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-FUTURES] "
      auto_start: true
    - id: binance-futures-log-ada
      providers:
        - binance-futures
      symbol: ADA-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-FUTURES] "
      auto_start: true
    - id: binance-futures-log-doge
      providers:
        - binance-futures
      symbol: DOGE-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-FUTURES] "
      auto_start: true
    - id: binance-futures-log-matic
      providers:
        - binance-futures
      symbol: MATIC-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-FUTURES] "
      auto_start: true
    - id: binance-futures-log-op
      providers:
        - binance-futures
      symbol: OP-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-FUTURES] "
      auto_start: true
    - id: binance-futures-log-arb
      providers:
        - binance-futures
      symbol: ARB-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-FUTURES] "
      auto_start: true
    - id: binance-futures-log-inj
      providers:
        - binance-futures
      symbol: INJ-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-FUTURES] "
      auto_start: true
    - id: binance-futures-log-gmx
      providers:
        - binance-futures
      symbol: GMX-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-FUTURES] "
      auto_start: true
    - id: binance-futures-log-rndr
      providers:
        - binance-futures
      symbol: RNDR-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-FUTURES] "
      auto_start: true
    - id: binance-futures-log-ldo
      providers:
        - binance-futures
      symbol: LDO-USDT
      strategy: logging
      config:
        dry_run: true
        logger_prefix: "[BINANCE-FUTURES] "
      auto_start: true
