eventbus:
  bufferSize: 5000
pools:
  eventSize: 20000
  orderRequestSize: 5000
telemetry:
  otlpEndpoint: http://capy.lan:4318
  serviceName: meltica-gateway
  otlpInsecure: true
  enableMetrics: true
