# environment: deployment environment (dev | staging | prod)
environment: dev

exchanges:
  # fake: synthetic market data source suitable for demos/tests
  fake:
    exchange:
      name: fake
      enabled: true
      ticker_interval: 100ms
      trade_interval: 100ms
      book_snapshot_interval: 100ms
  # fake-slow: alias with adjusted cadence, same underlying exchange implementation
  fake-slow:
    exchange:
      name: fake
      enabled: true
      ticker_interval: 250ms
      trade_interval: 500ms
      book_snapshot_interval: 250ms

# eventbus: in-memory event bus sizing
eventbus:
  bufferSize: 5000
  fanoutWorkers: 8

# pools: object pool capacities
pools:
  eventSize: 25000
  orderRequestSize: 5000

# apiServer: control API bind address (host:port or :port)
apiServer:
  addr: ":8880"

# telemetry: OTLP exporter configuration
telemetry:
  otlpEndpoint: http://capy.lan:4318
  serviceName: meltica-gateway
  otlpInsecure: true
  enableMetrics: true

# lambdaManifest: inline lambda definitions that will be materialised at startup
lambdaManifest:
  lambdas:
    - id: lambda-fake-btc
      provider: fake
      symbol: BTC-USDT
      strategy: delay
      config:
        min_delay: "250ms"
        max_delay: "750ms"
      auto_start: true
    - id: lambda-fake-btc-logger
      provider: fake
      symbol: BTC-USDT
      strategy: delay
      auto_start: true
    - id: lambda-fake-slow-eth
      provider: fake-slow
      symbol: ETH-USDT
      strategy: delay
      config:
        min_delay: "250ms"
        max_delay: "750ms"
      auto_start: true
    - id: lambda-fake-eth-noop
      provider: fake
      symbol: ETH-USDT
      strategy: delay
      auto_start: true
    - id: lambda-fake-xrp
      provider: fake
      symbol: XRP-USDT
      strategy: delay
      config:
        min_delay: "250ms"
        max_delay: "750ms"
      auto_start: true
    - id: lambda-fake-xrp-noop
      provider: fake
      symbol: XRP-USDT
      strategy: delay
      auto_start: true
    - id: lambda-fake-sol-1
      provider: fake
      symbol: SOL-USDT
      strategy: delay
      auto_start: true
    - id: lambda-fake-sol-2
      provider: fake
      symbol: SOL-USDT
      strategy: delay
      config:
        min_delay: "250ms"
        max_delay: "750ms"
      auto_start: true
    - id: lambda-fake-sol-3
      provider: fake
      symbol: SOL-USDT
      strategy: delay
      auto_start: true
    - id: lambda-fake-sol-4
      provider: fake
      symbol: SOL-USDT
      strategy: delay
      auto_start: true
    - id: lambda-fake-sol-logger
      provider: fake
      symbol: SOL-USDT
      strategy: delay
      auto_start: true
    - id: lambda-fake-ada
      provider: fake
      symbol: ADA-USDT
      strategy: delay
      config:
        min_delay: "250ms"
        max_delay: "750ms"
      auto_start: true
    - id: lambda-fake-ada-logger
      provider: fake
      symbol: ADA-USDT
      strategy: delay
      auto_start: true
    - id: lambda-fake-doge
      provider: fake
      symbol: DOGE-USDT
      strategy: delay
      auto_start: true
    - id: lambda-fake-doge-logger
      provider: fake
      symbol: DOGE-USDT
      strategy: delay
      auto_start: true
    - id: lambda-fake-bnb
      provider: fake
      symbol: BNB-USDT
      strategy: delay
      auto_start: true
    - id: lambda-fake-bnb-noop
      provider: fake
      symbol: BNB-USDT
      strategy: delay
      auto_start: true
    - id: lambda-fake-ltc
      provider: fake
      symbol: LTC-USDT
      strategy: delay
      auto_start: true
    - id: lambda-fake-ltc-logger
      provider: fake
      symbol: LTC-USDT
      strategy: delay
      auto_start: true
    - id: lambda-fake-dot
      provider: fake
      symbol: DOT-USDT
      strategy: delay
      auto_start: true
    - id: lambda-fake-dot-noop
      provider: fake
      symbol: DOT-USDT
      strategy: delay
      auto_start: true
    - id: lambda-fake-avax
      provider: fake
      symbol: AVAX-USDT
      strategy: delay
      auto_start: true
    - id: lambda-fake-avax-logger
      provider: fake
      symbol: AVAX-USDT
      strategy: delay
      auto_start: true
