# environment: deployment environment (dev | staging | prod)
environment: dev

exchanges:
  # fake-liquid: moderate volatility venue demonstrating instrument refresh and klines
  fake-liquid:
    exchange:
      name: fake
      enabled: true
      ticker_interval: 150ms
      trade_interval: 120ms
      book_snapshot_interval: 400ms
      instrument_refresh_interval: 15m
      kline_interval: 30s
      balance_update_interval: 2s
      price_model:
        drift: 0.00018
        volatility: 0.009
        shock_probability: 0.02
        shock_magnitude: 0.015
      trade_model:
        min_quantity: 0.02
        max_quantity: 1.5
      order_book:
        levels: 14
        max_mutation_width: 6
      venue_behavior:
        latency_min: 8ms
        latency_max: 28ms
        transient_error: 0.0025
        disconnect_chance: 0.0002
        disconnect_for: 2s
  # fake-volatile: fast-moving market with aggressive shocks for stress tests
  fake-volatile:
    exchange:
      name: fake
      enabled: true
      ticker_interval: 80ms
      trade_interval: 60ms
      book_snapshot_interval: 200ms
      kline_interval: 15s
      balance_update_interval: 1500ms
      price_model:
        drift: 0.00035
        volatility: 0.02
        shock_probability: 0.08
        shock_magnitude: 0.05
      trade_model:
        min_quantity: 0.01
        max_quantity: 2.8
      order_book:
        levels: 18
        max_mutation_width: 9
      venue_behavior:
        latency_min: 4ms
        latency_max: 18ms
        transient_error: 0.006
        disconnect_chance: 0.001
        disconnect_for: 1500ms
  # fake-calm: slower venue illustrating tight error budgets and wider latency bands
  fake-calm:
    exchange:
      name: fake
      enabled: true
      ticker_interval: 250ms
      trade_interval: 250ms
      book_snapshot_interval: 1s
      instrument_refresh_interval: 20m
      kline_interval: 1m
      balance_update_interval: 4s
      price_model:
        drift: 0.00005
        volatility: 0.004
        shock_probability: 0.01
        shock_magnitude: 0.01
      trade_model:
        min_quantity: 0.05
        max_quantity: 1.0
      order_book:
        levels: 10
        max_mutation_width: 4
      venue_behavior:
        latency_min: 12ms
        latency_max: 45ms
        transient_error: 0.0015
        disconnect_chance: 0.00005
        disconnect_for: 4s

# eventbus: in-memory event bus sizing
eventbus:
  bufferSize: 25000
  fanoutWorkers: 8

# pools: object pool capacities
pools:
  eventSize: 25000
  orderRequestSize: 25000

# apiServer: control API bind address (host:port or :port)
apiServer:
  addr: ":8880"

# telemetry: OTLP exporter configuration
telemetry:
  otlpEndpoint: http://capy.lan:4318
  serviceName: meltica-gateway
  otlpInsecure: true
  enableMetrics: true

# lambdaManifest: inline lambda definitions that will be materialised at startup
lambdaManifest:
  lambdas:
    - id: mm-btc
      provider: fake-liquid
      symbol: BTC-USDT
      strategy: marketmaking
      config:
        spread_bps: 28
        order_size: "0.05"
        max_open_orders: 3
      auto_start: true
    - id: grid-eth
      provider: fake-volatile
      symbol: ETH-USDT
      strategy: grid
      config:
        grid_levels: 5
        grid_spacing: 0.75
        order_size: "0.4"
      auto_start: true
    - id: momentum-sol
      provider: fake-volatile
      symbol: SOL-USDT
      strategy: momentum
      config:
        lookback_period: 24
        momentum_threshold: 0.9
        order_size: "12"
        cooldown: "4s"
      auto_start: true
    - id: meanrev-xrp
      provider: fake-calm
      symbol: XRP-USDT
      strategy: meanreversion
      config:
        window_size: 30
        deviation_threshold: 0.7
        order_size: "2500"
      auto_start: true
    - id: logging-ada
      provider: fake-liquid
      symbol: ADA-USDT
      strategy: logging
      config:
        logger_prefix: "[ADA-LOGGER] "
      auto_start: true
    - id: delay-doge
      provider: fake-calm
      symbol: DOGE-USDT
      strategy: delay
      config:
        min_delay: "150ms"
        max_delay: "600ms"
      auto_start: true
    - id: noop-bnb
      provider: fake-liquid
      symbol: BNB-USDT
      strategy: noop
      auto_start: true
    - id: mm-eth-tight
      provider: fake-liquid
      symbol: ETH-USDT
      strategy: marketmaking
      config:
        spread_bps: 18
        order_size: "0.08"
        max_open_orders: 2
      auto_start: true
    - id: grid-avax-wide
      provider: fake-calm
      symbol: AVAX-USDT
      strategy: grid
      config:
        grid_levels: 7
        grid_spacing: 1.1
        order_size: "0.75"
        base_price: 38.5
      auto_start: true
    - id: momentum-doge-fast
      provider: fake-volatile
      symbol: DOGE-USDT
      strategy: momentum
      config:
        lookback_period: 12
        momentum_threshold: 0.35
        order_size: "3500"
        cooldown: "2s"
      auto_start: false
    - id: meanrev-btc-calm
      provider: fake-calm
      symbol: BTC-USDT
      strategy: meanreversion
      config:
        window_size: 45
        deviation_threshold: 0.55
        order_size: "0.02"
      auto_start: false
    - id: logging-portfolio
      provider: fake-volatile
      symbol: ETH-USDT
      strategy: logging
      config:
        logger_prefix: "[VOLATILE-LOGGER] "
      auto_start: true
    - id: delay-dot-sweeper
      provider: fake-liquid
      symbol: DOT-USDT
      strategy: delay
      config:
        min_delay: "100ms"
        max_delay: "400ms"
      auto_start: true
    - id: mm-avax-volatile
      provider: fake-volatile
      symbol: AVAX-USDT
      strategy: marketmaking
      config:
        spread_bps: 35
        order_size: "0.6"
        max_open_orders: 4
      auto_start: false
    - id: mm-sol-calm
      provider: fake-calm
      symbol: SOL-USDT
      strategy: marketmaking
      config:
        spread_bps: 42
        order_size: "1.5"
        max_open_orders: 1
      auto_start: false
    - id: grid-ltc-liquid
      provider: fake-liquid
      symbol: LTC-USDT
      strategy: grid
      config:
        grid_levels: 6
        grid_spacing: 0.9
        order_size: "0.3"
      auto_start: true
    - id: momentum-bnb-liquid
      provider: fake-liquid
      symbol: BNB-USDT
      strategy: momentum
      config:
        lookback_period: 18
        momentum_threshold: 0.6
        order_size: "9"
        cooldown: "3s"
      auto_start: false
    - id: momentum-ada-calm
      provider: fake-calm
      symbol: ADA-USDT
      strategy: momentum
      config:
        lookback_period: 36
        momentum_threshold: 0.25
        order_size: "4200"
        cooldown: "6s"
      auto_start: true
    - id: meanrev-sol-liquid
      provider: fake-liquid
      symbol: SOL-USDT
      strategy: meanreversion
      config:
        window_size: 28
        deviation_threshold: 0.65
        order_size: "8"
      auto_start: false
    - id: meanrev-avax-volatile
      provider: fake-volatile
      symbol: AVAX-USDT
      strategy: meanreversion
      config:
        window_size: 32
        deviation_threshold: 0.8
        order_size: "0.9"
      auto_start: true
    - id: logging-calm-hub
      provider: fake-calm
      symbol: BTC-USDT
      strategy: logging
      config:
        logger_prefix: "[CALM-LOGGER] "
      auto_start: true
    - id: delay-eth-volatile
      provider: fake-volatile
      symbol: ETH-USDT
      strategy: delay
      config:
        min_delay: "80ms"
        max_delay: "320ms"
      auto_start: true
    - id: noop-avax-volatile
      provider: fake-volatile
      symbol: AVAX-USDT
      strategy: noop
      auto_start: false
    - id: noop-ada-calm
      provider: fake-calm
      symbol: ADA-USDT
      strategy: noop
      auto_start: false
