# environment: deployment environment (dev | staging | prod)
environment: dev

exchanges:
  # fake: synthetic market data source suitable for demos/tests
  fake:
    exchange:
      name: fake
      enabled: true
      ticker_interval: 100ms
      trade_interval: 100ms
      book_snapshot_interval: 100ms
  # fake-slow: alias with adjusted cadence, same underlying exchange implementation
  fake-slow:
    exchange:
      name: fake
      enabled: true
      ticker_interval: 250ms
      trade_interval: 500ms
      book_snapshot_interval: 250ms

# eventbus: in-memory event bus sizing
eventbus:
  bufferSize: 5000
  fanoutWorkers: 8

# pools: object pool capacities
pools:
  eventSize: 25000
  orderRequestSize: 5000

# apiServer: control API bind address (host:port or :port)
apiServer:
  addr: ":8880"

# telemetry: OTLP exporter configuration
telemetry:
  otlpEndpoint: http://capy.lan:4318
  serviceName: meltica-gateway
  otlpInsecure: true
  enableMetrics: true

# lambdaManifest: path to lambda manifest file
lambdaManifest: config/lambda-manifest.yaml
