# Meltica application configuration example.

# environment: deployment environment (dev | staging | prod)
environment: prod

exchanges:
  # fake: synthetic market-data provider (alias pointing to the "fake" exchange)
  fake:
    exchange:
      name: fake
      enabled: true
      ticker_interval: 500ms
      trade_interval: 1s
      book_snapshot_interval: 5s

  # fake-slow: alias with different cadence but the same underlying exchange implementation
  fake-slow:
    exchange:
      name: fake
      ticker_interval: 750ms
      trade_interval: 2s
      book_snapshot_interval: 10s

  # bnx/binance/BINANCE: demonstrate aliases mapping to the real Binance exchange
  bnx:
    exchange:
      name: binance
      venue: spot
  binance:
    exchange:
      name: binance
      venue: spot
  BINANCE:
    exchange:
      name: binance
      venue: futures

# eventbus: in-memory event bus configuration
eventbus:
  bufferSize: 2048
  fanoutWorkers: 8

# pools: configure object pool capacities
pools:
  eventSize: 50000
  orderRequestSize: 10000

# apiServer: control API bind address (host:port or :port)
apiServer:
  addr: ":8880"

# telemetry: OTLP exporter configuration
telemetry:
  otlpEndpoint: http://localhost:4318
  serviceName: meltica-gateway
  otlpInsecure: true
  enableMetrics: true

# lambdaManifest: path to lambda manifest file
lambdaManifest: config/lambda-manifest.yaml
