environment: prod

providers:
  binance:
    exchange:
      name: binance
      venue: spot
      enabled: true
      snapshot_depth: 100
  binance-futures:
    exchange:
      name: binance
      venue: futures
      enabled: true
      snapshot_depth: 100
  binance-futures-coin:
    exchange:
      name: binance
      venue: coin
      enabled: true
      snapshot_depth: 100

eventbus:
  bufferSize: 8192
  fanoutWorkers: auto

pools:
  event:
    size: 60000
    waitQueueSize: 60000
  orderRequest:
    size: 20000
    waitQueueSize: 20000

risk:
  maxPositionSize: "100"
  maxNotionalValue: "25000"
  notionalCurrency: "USDT"
  orderThrottle: 2.5
  orderBurst: 2
  maxConcurrentOrders: 5
  priceBandPercent: 0.8
  allowedOrderTypes:
    - Limit
    - Market
  killSwitchEnabled: true
  maxRiskBreaches: 3
  circuitBreaker:
    enabled: true
    threshold: 4
    cooldown: 60s

apiServer:
  addr: ":8880"

telemetry:
  otlpEndpoint: http://capy.lan:4318
  serviceName: meltica-gateway-binance
  otlpInsecure: true
  enableMetrics: true

lambdaManifest:
  lambdas:
    - id: binance-logging-btc
      providers:
        binance:
          symbols:
            - BTC-USDT
        binance-futures:
          symbols:
            - BTC-USDT
        binance-futures-coin:
          symbols:
            - BTC-USD
      strategy: logging
      config:
        dry_run: true
      auto_start: true
