environment: dev

meta:
  name: Meltica Gateway
  version: v1
  description: Trading control plane

runtime:
  eventbus:
    buffer_size: 8192
    fanout_workers: 8

  pools:
    event:
      size: 8192
      wait_queue_size: 8192
    order_request:
      size: 4096
      wait_queue_size: 4096

  api_server:
    addr: ":8880"

  telemetry:
    otlp_endpoint: http://capy.lan:4318
    service_name: meltica-gateway
    otlp_insecure: true
    enable_metrics: true
