environment: dev

meta:
  name: Meltica Gateway
  version: v1
  description: Trading control plane

runtime:
  eventbus:
    buffer_size: 8192
    fanout_workers: 8

  pools:
    event:
      size: 8192
      wait_queue_size: 8192
    order_request:
      size: 4096
      wait_queue_size: 4096

  risk:
    max_position_size: "250"
    max_notional_value: "50000"
    notional_currency: "USDT"
    order_throttle: 5
    order_burst: 3
    max_concurrent_orders: 6
    price_band_percent: 1.0
    allowed_order_types:
      - Limit
      - Market
    kill_switch_enabled: true
    max_risk_breaches: 3
    circuit_breaker:
      enabled: true
      threshold: 4
      cooldown: 90s

  api_server:
    addr: ":8880"

  telemetry:
    otlp_endpoint: http://capy.lan:4318
    service_name: meltica-gateway
    otlp_insecure: true
    enable_metrics: true
