# environment: deployment environment (dev | staging | prod)
environment: dev

# eventbus: in-memory event bus sizing
eventbus:
  bufferSize: 8192
  fanoutWorkers: 8

# pools: object pool capacities
pools:
  event:
    size: 8192
    waitQueueSize: 8192
  orderRequest:
    size: 4096
    waitQueueSize: 4096

# apiServer: control API bind address (host:port or :port)
apiServer:
  addr: ":8880"

# telemetry: OTLP exporter configuration
telemetry:
  otlpEndpoint: http://capy.lan:4318
  serviceName: meltica-gateway
  otlpInsecure: true
  enableMetrics: true
