# Meltica application configuration example.

# environment: deployment environment (dev | staging | prod)
environment: prod

providers:
  # fake: synthetic market-data provider (alias pointing to the "fake" exchange)
  fake:
    exchange:
      name: fake
      enabled: true
      ticker_interval: 500ms
      trade_interval: 1s
      book_snapshot_interval: 5s
      balance_update_interval: 3s

  # fake-slow: alias with different cadence but the same underlying exchange implementation
  fake-slow:
    exchange:
      name: fake
      ticker_interval: 750ms
      trade_interval: 2s
      book_snapshot_interval: 10s
      balance_update_interval: 6s

  # bnx/binance/BINANCE: demonstrate aliases mapping to the real Binance exchange
  bnx:
    exchange:
      name: binance
      venue: spot
  binance:
    exchange:
      name: binance
      venue: spot
  BINANCE:
    exchange:
      name: binance
      venue: futures

# eventbus: in-memory event bus configuration
eventbus:
  bufferSize: 2048
  fanoutWorkers: 8

# pools: configure object pool capacities
pools:
  eventSize: 50000
  orderRequestSize: 10000

risk:
  maxPositionSize: "250"
  maxNotionalValue: "50000"
  notionalCurrency: "USDT"
  orderThrottle: 5
  orderBurst: 3
  maxConcurrentOrders: 8
  priceBandPercent: 1.0
  allowedOrderTypes:
    - Limit
    - Market
  killSwitchEnabled: true
  maxRiskBreaches: 5
  circuitBreaker:
    enabled: true
    threshold: 6
    cooldown: 90s

# apiServer: control API bind address (host:port or :port)
apiServer:
  addr: ":8880"

# telemetry: OTLP exporter configuration
telemetry:
  otlpEndpoint: http://localhost:4318
  serviceName: meltica-gateway
  otlpInsecure: true
  enableMetrics: true

# lambdaManifest: inline lambda definitions that will be materialised at startup
lambdaManifest:
  lambdas:
    - id: lambda-fake-btc
      providers:
        - fake
      symbol: BTC-USDT
      strategy: delay
      config:
        dry_run: true
        min_delay: "250ms"
        max_delay: "750ms"
      auto_start: true
    - id: lambda-fake-btc-logger
      providers:
        - fake
      symbol: BTC-USDT
      strategy: delay
      config:
        dry_run: true
      auto_start: true
    - id: lambda-fake-slow-eth
      providers:
        - fake-slow
      symbol: ETH-USDT
      strategy: delay
      config:
        dry_run: true
        min_delay: "250ms"
        max_delay: "750ms"
      auto_start: true
    - id: lambda-fake-eth-noop
      providers:
        - fake
      symbol: ETH-USDT
      strategy: delay
      config:
        dry_run: true
      auto_start: true
    - id: lambda-fake-xrp
      providers:
        - fake
      symbol: XRP-USDT
      strategy: delay
      config:
        dry_run: true
        min_delay: "250ms"
        max_delay: "750ms"
      auto_start: true
    - id: lambda-fake-xrp-noop
      providers:
        - fake
      symbol: XRP-USDT
      strategy: delay
      config:
        dry_run: true
      auto_start: true
    - id: lambda-fake-sol-1
      providers:
        - fake
      symbol: SOL-USDT
      strategy: delay
      config:
        dry_run: true
      auto_start: true
    - id: lambda-fake-sol-2
      providers:
        - fake
      symbol: SOL-USDT
      strategy: delay
      config:
        dry_run: true
        min_delay: "250ms"
        max_delay: "750ms"
      auto_start: true
    - id: lambda-fake-sol-3
      providers:
        - fake
      symbol: SOL-USDT
      strategy: delay
      config:
        dry_run: true
      auto_start: true
    - id: lambda-fake-sol-4
      providers:
        - fake
      symbol: SOL-USDT
      strategy: delay
      config:
        dry_run: true
      auto_start: true
    - id: lambda-fake-sol-logger
      providers:
        - fake
      symbol: SOL-USDT
      strategy: delay
      config:
        dry_run: true
      auto_start: true
    - id: lambda-fake-ada
      providers:
        - fake
      symbol: ADA-USDT
      strategy: delay
      config:
        dry_run: true
        min_delay: "250ms"
        max_delay: "750ms"
      auto_start: true
    - id: lambda-fake-ada-logger
      providers:
        - fake
      symbol: ADA-USDT
      strategy: delay
      config:
        dry_run: true
      auto_start: true
    - id: lambda-fake-doge
      providers:
        - fake
      symbol: DOGE-USDT
      strategy: delay
      config:
        dry_run: true
      auto_start: true
    - id: lambda-fake-doge-logger
      providers:
        - fake
      symbol: DOGE-USDT
      strategy: delay
      config:
        dry_run: true
      auto_start: true
    - id: lambda-fake-bnb
      providers:
        - fake
      symbol: BNB-USDT
      strategy: delay
      config:
        dry_run: true
      auto_start: true
    - id: lambda-fake-bnb-noop
      providers:
        - fake
      symbol: BNB-USDT
      strategy: delay
      config:
        dry_run: true
      auto_start: true
    - id: lambda-fake-ltc
      providers:
        - fake
      symbol: LTC-USDT
      strategy: delay
      config:
        dry_run: true
      auto_start: true
    - id: lambda-fake-ltc-logger
      providers:
        - fake
      symbol: LTC-USDT
      strategy: delay
      config:
        dry_run: true
      auto_start: true
    - id: lambda-fake-dot
      providers:
        - fake
      symbol: DOT-USDT
      strategy: delay
      config:
        dry_run: true
      auto_start: true
    - id: lambda-fake-dot-noop
      providers:
        - fake
      symbol: DOT-USDT
      strategy: delay
      config:
        dry_run: true
      auto_start: true
    - id: lambda-fake-avax
      providers:
        - fake
      symbol: AVAX-USDT
      strategy: delay
      config:
        dry_run: true
      auto_start: true
    - id: lambda-fake-avax-logger
      providers:
        - fake
      symbol: AVAX-USDT
      strategy: delay
      config:
        dry_run: true
      auto_start: true
