adapter:
  binance:
    ws:
      publicUrl: wss://stream.binance.com:9443/stream
      handshakeTimeout: 10s
    rest:
      snapshot:
        endpoint: /api/v3/depth
        interval: 5s
        limit: 100
dispatcher:
  routes:
    TICKER:
      wsTopics:
        - ticker.BTCUSDT
        - ticker.ETHUSDT
      restFns: []
      filters:
        - field: instrument
          op: eq
          value: BTC-USDT
    ORDERBOOK.DELTA:
      wsTopics:
        - depth.BTCUSDT
        - depth.ETHUSDT
      restFns:
        - name: orderbookSnapshot
          endpoint: /api/v3/depth
          interval: 5s
          parser: orderbook
      filters:
        - field: market
          op: eq
          value: BINANCE-SPOT
snapshot:
  ttl: 15m
databus:
  bufferSize: 1024
  perInstrument: 16
telemetry:
  otlpEndpoint: http://localhost:4318
  serviceName: meltica-gateway
