adapter:
  binance:
    ws:
      publicUrl: wss://stream.binance.com:9443/stream
      handshakeTimeout: 10s
    rest:
      snapshot:
        endpoint: /api/v3/depth
        interval: 5s
        limit: 100
dispatcher:
  routes:
    TICKER:
      wsTopics:
        - btcusdt@ticker
        - ethusdt@ticker
        - xrpusdt@ticker
      restFns: []
      filters:
        - field: instrument
          op: in
          value:
            - BTC-USDT
            - ETH-USDT
            - XRP-USDT
    TRADE:
      wsTopics:
        - btcusdt@aggTrade
        - ethusdt@aggTrade
        - xrpusdt@aggTrade
      restFns: []
      filters:
        - field: instrument
          op: in
          value:
            - BTC-USDT
            - ETH-USDT
            - XRP-USDT
    ORDERBOOK.DELTA:
      wsTopics:
        - btcusdt@depth@100ms
        - ethusdt@depth@100ms
        - xrpusdt@depth@100ms
      filters:
        - field: instrument
          op: in
          value:
            - BTC-USDT
            - ETH-USDT
            - XRP-USDT
snapshot:
  ttl: 15m
eventbus:
  bufferSize: 1024
  perInstrument: 16
telemetry:
  otlpEndpoint: http://capy.lan:4318
  serviceName: meltica-gateway
  otlpInsecure: true
  enableMetrics: true # Metrics only - no traces/Jaeger
